### ISSUE TITLE
websocket connection on melodic

### ISSUE THREAD

**Issue by bbferka** [RobotWebTools/rosbridge_suite#342]
Hi, 

I am trying rosbridge out on a fresh install of 18.04 and Melodic, but I can't seem to be able to connect using websockets.I compiled rosbirdge_suite from source (master branch) and its dependencies (namely rosauth/master) and used rosdep to install any system dependencies that might exist. 

Running the simple tutorial from [here](http://wiki.ros.org/roslibjs/Tutorials/BasicRosFunctionality) I keep getting the following error:

`Connected to websocket server. test.html:18:5
The connection to ws://localhost:9090/ was interrupted while the page was loading. roslib.min.js:1:19480
Error connecting to websocket server:  
`
```yaml

{ target: WebSocket, 
  isTrusted: true, 
  currentTarget: WebSocket, 
  eventPhase: 2, 
  bubbles: false,
  cancelable: false,  
  defaultPrevented: false, 
  composed: false, 
  timeStamp: 225,
  cancelBubble: false, … }
  test.html:22:5

```
Maybe i forgot to install something? I am unsure. This works perfectly fine on 16.04; I tried running the unit tests that come with `rosbridge_library` and they all pass. 

Any help would be much appreciated. 

Cheers!
