### ISSUE TITLE
Exception calling subscribe callback: 'float' object has no attribute 'get_fields_and_field_types'

### ISSUE THREAD

**Issue by owen7900** [RobotWebTools/rosbridge_suite#512]
## Expected Behavior
Sending rmf_fleet_msgs/FleetState messages through the websocket to the front end.

## Actual Behavior
Subscribe is failing giving this error message 
```
---
stamp:
  sec: 1593087409
  nanosec: 113872237
level: 40
name: rosbridge_websocket
msg: 'Exception calling subscribe callback: ''float'' object has no attribute ''get_fields_and_field_types'''
file: /home/owen/server_ws/install/rosbridge_library/lib/python3.6/site-packages/rosbridge_library/internal/subscribers.py
function: callback
line: 192
---
```
This only occurs when the FleetState message has robots in the Array of Robot states. when the Array is empty there is no problem.

## Steps to Reproduce the Problem

  1.Use roslibjs to subscribe to a topic publishing an rmf_fleet_msgs/FleetState message
  2.Send a FleetState message with a non-empty RobotState Array

## Specifications

  - ROS Version (`echo $ROS_DISTRO`): Ros2 Eloquent
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): Bionic 
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): ros2 branch built from source
  - Twisted Version (`python -c 'import twisted; print twisted.version'`): 17.9.0
