### ISSUE TITLE
Building from source + Docker

### ISSUE THREAD

**Issue by pltlg** [RobotWebTools/rosbridge_suite#563]
I followed the instructions how to build rosbridge from source but the container always run into the following error:
```
RLException: Unable to launch [rosbridge_websocket-1].
If it is a script, you may be missing a '#!' declaration at the top.
The traceback for the exception was written to the log file
... logging to /root/.ros/log/fa2f30e6-80bf-11eb-a895-0242c0a82002/roslaunch-a159d6b168ce-1.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://rosbridge:39387/

SUMMARY
========

PARAMETERS
 * /rosapi/params_glob: [*]
 * /rosapi/services_glob: [*]
 * /rosapi/topics_glob: [*]
 * /rosbridge_websocket/address: 0.0.0.0
 * /rosbridge_websocket/authenticate: False
 * /rosbridge_websocket/bson_only_mode: False
 * /rosbridge_websocket/delay_between_messages: 0
 * /rosbridge_websocket/fragment_timeout: 600
 * /rosbridge_websocket/max_message_size: None
 * /rosbridge_websocket/params_glob: [*]
 * /rosbridge_websocket/port: 9090
 * /rosbridge_websocket/retry_startup_delay: 5
 * /rosbridge_websocket/services_glob: [*]
 * /rosbridge_websocket/topics_glob: [*]
 * /rosbridge_websocket/unregister_timeout: 10
 * /rosbridge_websocket/use_compression: False
 * /rosbridge_websocket/websocket_external_port: 9090
 * /rosbridge_websocket/websocket_ping_interval: 0
 * /rosbridge_websocket/websocket_ping_timeout: 30
 * /rosdistro: melodic
 * /rosversion: 1.14.10

NODES
  /
    rosapi (rosapi/rosapi_node)
    rosbridge_websocket (rosbridge_server/rosbridge_websocket)

ROS_MASTER_URI=http://ros-master:11311

[rosbridge_websocket-1] killing on exit
```

When apt-get is used in dockerfile it works perfectly.
The "build from source" dockerfile: (I added the rosbridge_suite as a submodule to my private repo under stc/bridge)
```
ARG ARCH=
FROM ${ARCH}/ros:melodic

RUN sh -c 'echo "deb http://packages.ros.org/ros/ubuntu `lsb_release -sc` main" > /etc/apt/sources.list.d/ros-latest.list'
RUN apt-get update && apt-get install -y \
    wget \
	ros-melodic-rosauth \
 && rm -rf /var/lib/apt/lists/*
    
RUN wget http://packages.ros.org/ros.key -O - | sudo apt-key add -
RUN chmod -R 700 /opt/ros/melodic
RUN echo "/opt/ros/melodic/setup.bash" >> ~/.bashrc
RUN chmod 700 ~/.bashrc
RUN ~/.bashrc

# Booststrap workspace.
ENV CATKIN_DIR=/wss/bridge_ws
RUN mkdir -p $CATKIN_DIR
COPY . $CATKIN_DIR

RUN . /opt/ros/melodic/setup.sh \
 && cd $CATKIN_DIR/src \
 && catkin_init_workspace
WORKDIR $CATKIN_DIR

COPY src/bridge/rosbridge_suite src/rosbridge_suite
COPY src/bridge/rosbridge_library src/rosbridge_library
COPY src/bridge/rosbridge_server src/rosbridge_server
COPY src/bridge/rosbridge_msgs src/rosbridge_msgs
COPY src/bridge/rosapi /wss/bridge_ws/src/rosapi

RUN rm -r src/bridge

RUN . /opt/ros/melodic/setup.sh \
 && apt-get update \
 && rosdep update \
 && rosdep install \
    --from-paths src \
    --ignore-src \
    --rosdistro melodic \
    -r \
    -y \
 && rm -rf /var/lib/apt/lists/*

RUN . /opt/ros/melodic/setup.sh \
 && catkin_make
```

I use the following docker-compose yml:
``` yaml
version: '2'
networks:
  ros:
    driver: bridge
services:
  ros-master:
    image: ros:melodic
    container_name: ros-master
    command: stdbuf -o L roscore
    networks:
      - ros
    restart: always
  rosbridge:
    image: rosbridge
    container_name: rosbridge
    depends_on:
      - ros-master
    environment:
      - "ROS_MASTER_URI=http://ros-master:11311"
      - "ROS_HOSTNAME=rosbridge"
    networks:
      - ros
    ports:
    - "9090:9090"
    restart: always
    command: >
      bash -c "source /opt/ros/melodic/setup.bash 
      && source /wss/bridge_ws/devel/setup.bash
      && chmod -R +x .
      && roslaunch rosbridge_server rosbridge_websocket.launch"
```

## Steps to Reproduce the Problem
Assuming that you have docker and docker-compose installed

  1. Create a workspace folder
  2. Clone the rosbridge_suite repository into stc/bridge folder
  3. Download the dockerfile into to root of the workspace
  4. Run ``` docker build -t rosbridge -f ./Dockerfile --build-arg ARCH=amd64 . ```
  5. Run the docker-compose file ``` docker-compose up -d ```
  
You can see the error message by running ```  docker container logs rosbridge ```
