### ISSUE TITLE
InvalidServiceException: Service /rosapi/topics_and_raw_types does not exist (Docker + Fast-DDS Discovery Server)

### ISSUE THREAD

**Issue by kledom** [RobotWebTools/rosbridge_suite#791]
**Description**

I'm running ROS2 humble using [Fast-DDS discovery Server](https://docs.ros.org/en/humble/Tutorials/Advanced/Discovery-Server/Discovery-Server.html). This is necessary because I want to deploy ROS over a VPN that does not support multicast. To make things even more complicated, I would also like to use docker-compose.

I have a docker-compose file as a template that I am absolutely sure of that it works with basic ROS2 nodes (e.g.  demo_nodes_cpp talker and listener). In fact, I've already deployed it several times in similar scenarios. However, using it with rosbridge_suite leads to errors.

- Library Version: 1.3.0
- ROS Version: humble
- Platform / OS: Ubuntu 22.04 (Host), ros:humble-ros-core (Container)
- rosbridge_suite client: e.g. foxglove-studio.

**Steps To Reproduce**

Dockerfile
```
ARG ROS_VERSION=humble
FROM ros:${ROS_VERSION}-ros-core

ARG ROS_VERSION

# Install rosbridge_suite
RUN apt-get update -qq && \
    apt-get install -y ros-${ROS_VERSION}-rosbridge-server && \
    rm -rf /var/lib/apt/lists/*

CMD ["ros2", "launch", "rosbridge_server", "rosbridge_websocket_launch.xml"]
```

docker-compose.yml
```
version: "3.3"

services:
  discovery:
    image: ros:humble-ros-core
    command: fastdds discovery -i 0 -p 11811
    network_mode: host

  bridge_suite:
    depends_on:
      - discovery
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - RMW_IMPLEMENTATION=rmw_fastrtps_cpp
      - FASTRTPS_DEFAULT_PROFILES_FILE=/dds_config.xml
      - ROS_DISCOVERY_SERVER=127.0.0.1:11811
      - PYTHONUNBUFFERED=1
    volumes:
      - ${PWD}/fastRTPS_no_SHM.xml:/dds_config.xml
    network_mode: host
```

fastRTPS_no_SHM.xml

- (disable shared memory transport, currently required, I don't like it either)

```
<?xml version="1.0" encoding="UTF-8" ?>
<dds>
    <profiles xmlns="http://www.eprosima.com/XMLSchemas/fastRTPS_Profiles">
        <transport_descriptors>
            <transport_descriptor>
                <transport_id>udp_transport</transport_id>
                <type>UDPv4</type>
            </transport_descriptor>
        </transport_descriptors>
        <participant profile_name="participant_profile" is_default_profile="true">
            <rtps>
                <userTransports>
                    <transport_id>udp_transport</transport_id>
                </userTransports>
                <useBuiltinTransports>false</useBuiltinTransports>
            </rtps>
        </participant>
    </profiles>
</dds>
```

**Expected Behavior**

Client connects to rosbridge_suite successfully.

**Actual Behavior**

Starting rosbridge_suite with `ros2 launch rosbridge_server rosbridge_websocket_launch.xml` does not produce any noticeable output. However, as soon as a clients connects, the following error message gets printed repeatedly:

> [Client 2f57dba0-9163-4c9d-9ee2-eb9a814351ed] [id: call_service:/rosapi/topics_and_raw_types:4] call_service InvalidServiceException: Service /rosapi/topics_and_raw_types does not exist

Without the environment variable ROS_DISCOVERY_SERVER everything works as expected. But of course the Discovery Server is not used then.
